header:
  version: 11

machine: gateway-dk
distro: recovery

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: "2.18"
    path: sources/bitbake
    layers:
      .: "disabled"

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: wrynose
    path: sources/openembedded-core
    layers:
      meta:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: wrynose
    path: sources/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  meta-mono:
    path: .

target:
  - recovery-image
  - firmware-image

local_conf_header:
  site: |
    require ${TOPDIR}/../site.conf
