BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mono"
BBFILE_PATTERN_meta-mono = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mono = "10"

# Let recipes reference files elsewhere in this layer by absolute path.
LAYERDIR_meta-mono = "${LAYERDIR}"

LAYERDEPENDS_meta-mono = "core openembedded-layer networking-layer"
LAYERSERIES_COMPAT_meta-mono = "wrynose"