#!/bin/sh

case "$1" in
    start)
        echo "Starting fancontrol..."
        /usr/sbin/fancontrol &
        ;;
    stop)
        echo "Stopping fancontrol..."
        killall fancontrol
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0