#!/bin/sh

case "$1" in
    start)
        /usr/bin/status-led.sh
        ;;
    stop)
        # Nothing to do on stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0